version: '3'
services:
  frontend:
    build:
      context: ./carepal-fe
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./carepal-be
    env_file:
      - ./carepal-be/.env
    ports:
      - "5000:5000"
